apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: data/standard/default/pv-zookeeper
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem