apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: edge
spec:
  kafka:
    replicas: 3
    version: 3.3.1
    listeners: 
      - name: internal
        port: 29092
        type: internal
        tls: false 
      - name: external
        port: 9092
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: kafka.vms.com
          brokers:
          - broker: 0
            host: kafka-0.vms.com
          - broker: 1
            host: kafka-1.vms.com
          - broker: 2
            host: kafka-2.vms.com
    storage:
      type: persistent-claim
      size: 10Gi
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
  zookeeper:
    replicas: 3
    storage: 
      type: persistent-claim
      size: 10Gi